fusion--dev/src/objects/Quote_Header__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Header</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fusion--dev/src/classes/QuoteCommonUtil.cls
public class QuoteCommonUtil {
   
    
    public static String expireQuote(Id recordId) {
     try {
         Quote_Header__c QuoObj = [Select Id, Status__c From Quote_Header__c where Id =: recordId];
         QuoObj.Status__c = 'Expired';
         update QuoObj;
         return 'SUCCESS';
     } catch (Exception e) {
         System.debug('An unexpected error has occurred: ' + e.getMessage());
         return e.getMessage();
       }
     }

}